### ISSUE TITLE
Theme does not appear in DKG Theme Modifier

### ISSUE THREAD

**Issue by exoduscl** [davidkgriggs/XBOXSERIESish#1]
As of now the theme won't appear in the tabs of DKG.

![image](https://user-images.githubusercontent.com/69265795/143499902-739c8549-0343-4806-8bb9-35c70b39cc5e.png)

Thanks for your great work!

**Comment by davidkgriggs** [comment]
Support has not been added yet. The theme is still in Beta testing. Once it is added it'll be on the changelog for the DKG Theme Modifier.
