### ISSUE TITLE
Wired layout on 3:2 displays

### ISSUE THREAD

**Issue by PIndividual** [davidkgriggs/XBOXSERIESish#12]
![image](https://user-images.githubusercontent.com/62368342/153014813-23fd4e01-8f27-498a-bf30-b83b4ab0efc2.png)

**Comment by PIndividual** [comment]
Some apps are not being displayed, and the intro logo is also being pressed
![image](https://user-images.githubusercontent.com/62368342/153015351-07c4c502-6631-4348-92db-a5c8d7d015e1.png)

**Comment by davidkgriggs** [comment]
Unfortunately this theme won't work with 3:2 displays.
