### ISSUE TITLE
The theme starts on the all games screen

### ISSUE THREAD

**Issue by LuKa8989** [davidkgriggs/XBOXSERIESish#4]
It happens that the theme sometimes instead of starting on the dashboard starts up in the all games screen

**Comment by ShroudedBowman** [comment]
I have had this same issue on a few occasions. Usually after I have left full screen mode for desktop and then gone back into full screen from the desktop mode application

**Comment by davidkgriggs** [comment]
The All Games section is just the Layout being set to not Horizontal. If you leave the theme in All Games section when you exit the theme it will be on that section when you start the theme again.
